### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ludenticus** [RaphaelKimmig/Gnome-Presentation-Mode#1]
I tried to clone, but I got it (Fedora 15):

Cloning into Gnome-Presentation-Mode...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

How can I solve it?

Thanx

**Comment by christophlsa** [comment]
I think you used the wrong url. The error message says you are connecting to ssh.

Use this command instead:
`git clone git://github.com/RaphaelKimmig/Gnome-Presentation-Mode.git`
or
`git clone https://github.com/RaphaelKimmig/Gnome-Presentation-Mode.git`

**Comment by RaphaelKimmig** [comment]
I assume christophlsa is correct.
Thanks for being faster with supporting people than I am ;-)
I've corrected the README file.

**Comment by ludenticus** [comment]
I followed the kind reply of christophlsa, which I thank. However, I'm facing now another issue: basically, it's not working (the way it is supposed to). My guess is a conflict with the noally (fpmurphy) extension. It doesn't even show in the gnome-tweak-tool extension tab.

**Comment by christophlsa** [comment]
I also use the noally extension and this extensions does his job.

Did you open Looking Glass (alt+F2 -> "lg") and looked in the "Error" tab? There should be a error message if this extension could not load. (closing: go to "Evaluator" Tab and press ESC).

**Comment by RaphaelKimmig** [comment]
I assume you made a mistake while installing the extension - thus I suggest you open a new ticket and provide us 
a) with the output of the error shell as per christophlsas post
b) the contents of your gnome-shell extensions directory, that is the output of 

 `find  ~/.local/share/gnome-shell/extensions/`

If we are able to understand what went wrong I'll add hints to the instructions so that others don't run into the same problems.

Regards,

Raphael

**Comment by ludenticus** [comment]
I was about to post the output of the "Error" tab, but then I realized that the bug was already solved. It had to do with the Gnome-shell version issue.

I'd like to thank you both the replies

Eduardo
