### ISSUE TITLE
Don't have a battery icon!

### ISSUE THREAD

**Issue by 0rAX0** [RaphaelKimmig/Gnome-Presentation-Mode#10]
Hi, 

I tried this extension before on a desktop computer, which doesn't have a battery icon(of course). Can I use this extension then?

**Comment by darkxst** [comment]
edit this line 
`let batteryMenu = Main.panel._statusArea.battery;`   in extension.js 

to 

`let batteryMenu = Main.panel._statusArea.a11y;` (Will put it in the accessibility menu)

or

`let batteryMenu = Main.panel._statusArea.userMenu;` (Will put it in the User Menu)

**Comment by 0rAX0** [comment]
I think an auto-detect feature or a dconf setting would make things easier. :)

**Comment by Mystro256** [comment]
I have no interest in fixing this and I would rather just play with my fork instead: https://github.com/Mystro256/gnome-shell-extension-inhibit-applet

**Comment by Mystro256** [comment]
I plan to merge my fork into this, and this has already been fixed in my fork.

I'll close this for now, just use my fork until I get around to merging/pulling it:
https://github.com/Mystro256/gnome-shell-extension-inhibit-applet
https://extensions.gnome.org/extension/233/inhibit-applet/

Please re-open if it's not fixed in my fork
