### ISSUE TITLE
Remember presentation mode after reboot

### ISSUE THREAD

**Issue by gaborpapp** [RaphaelKimmig/Gnome-Presentation-Mode#13]
Is there a way to make the system stay in presentation mode after reboot? I'm using the latest git be7e0aea with gnome-shell 3.2.1 on Fedora 16.

**Comment by Mystro256** [comment]
As I said in the pull request, this does needs a new fix to work, as a lot of the code has been changed since then.
I hope to make settings for the following and would love some help if you're up to contributing:
- remember mode after reboot (default off)
- put switch in usermenu (default off)

Thanks for your input! I plan to look into this when I can :)

**Comment by Mystro256** [comment]
This is now fixed, thanks for the suggestion.

Also note, due to simplicity I decide to make it this functionality by default.

Thanks :)

**Comment by gaborpapp** [comment]
great! thanks.
