### ISSUE TITLE
Update to GNOME 3.4

### ISSUE THREAD

**Issue by kparal** [RaphaelKimmig/Gnome-Presentation-Mode#20]
Please update to GNOME 3.4 and post to extensions.gnome.org. Thanks.

**Comment by Mystro256** [comment]
I plan to merge my fork into this, and I've already done both this in my fork.

I'll close this for now, just use my fork until I get around to merging/pulling it:
https://github.com/Mystro256/gnome-shell-extension-inhibit-applet
https://extensions.gnome.org/extension/233/inhibit-applet/

Please re-open if it's not fixed in my fork
