### ISSUE TITLE
"Presentation mode" is a wrong name

### ISSUE THREAD

**Issue by geoffm** [RaphaelKimmig/Gnome-Presentation-Mode#6]
"Presentation mode" is neither explicit or intuitive. Usually presentation mode refers to apps displaying on full screen without menus and toolbars.
A few days after installing presentation mode I forgot what it was supposed to do and I had to do a search to find out.
It should be named after what it is, a power saving inhibiter:  "inhibit screen saver" or "inhibit suspend" or something like that.

**Comment by Mystro256** [comment]
I like "Disable Screensaver", sounds less esoteric and more self explanatory.

**Comment by Mystro256** [comment]
I plan to merge my fork into this, and I've already fixed this in my fork.

I'll close this for now, just use my fork until I get around to merging/pulling it:
https://github.com/Mystro256/gnome-shell-extension-inhibit-applet
https://extensions.gnome.org/extension/233/inhibit-applet/

Please re-open if it's not fixed in my fork
